// Generated by CoffeeScript 1.8.0
(function() {
  var client, connStr, pg;

  pg = require("pg");

  connStr = "postgres://postgres:20070428@localhost/test";

  client = new pg.Client(connStr);

  client.connect(function(err) {
    return client.query("select * from weather", function(err, result) {
      console.log(err, result.rows[0]);
      return client.end();
    });
  });

}).call(this);
