// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl;

  MemberCtrl = require("./../ctrl/memberCtrl");

  exports.dologin = function(req, res) {
    var passwd, userName;
    userName = req.body.userName;
    passwd = req.body.passwd;
    return MemberCtrl.login(userName, passwd, function(err, results) {
      if (err) {
        return res.redirect("/");
      } else {
        res.cookie("token", results.data.token);
        res.cookie("tokenExpires", results.data.expireDate);
        req.flash("token", results.data.token);
        req.flash("tokenExpires", results.data.expireDate);
        return res.redirect("/");
      }
    });
  };

  exports.dobind = function(req, res) {
    var openid, passwd, userName;
    userName = req.body.userName;
    passwd = req.body.passwd.toLowerCase();
    openid = req.body.openid;
    return MemberCtrl.weixinBind(userName, passwd, openid, function(err, results) {
      console.log(err, results);
      return res.json(results);
    });
  };

  exports.dologout = function(req, res) {
    res.clearCookie("token");
    res.clearCookie("tokenExpires");
    delete req.session.member;
    return res.redirect("/");
  };

}).call(this);
