// Generated by CoffeeScript 1.8.0
(function() {
  var CouponCtrl, CustomerCtrl, MemberCtrl, ProductCtrl, SettingCtrl, async;

  ProductCtrl = require("./../ctrl/productCtrl");

  CustomerCtrl = require("./../ctrl/customerCtrl");

  SettingCtrl = require("./../ctrl/settingCtrl");

  MemberCtrl = require("./../ctrl/memberCtrl");

  CouponCtrl = require("./../ctrl/couponCtrl");

  async = require("async");

  exports.dashboard = function(req, res) {
    return res.render("./page/dashboard");
  };

  exports.profile = function(req, res) {
    return res.render("./page/profile", {
      member: req.session.member
    });
  };

  exports.images = function(req, res) {
    return res.render("./page/images");
  };

  exports.setting = function(req, res) {
    return async.parallel([
      function(cb) {
        return SettingCtrl.webConfigDetail(req.session.member.ent._id, function(err, results) {
          return cb(err, results);
        });
      }, function(cb) {
        return SettingCtrl.weixinConfigDetail(req.session.member.ent._id, function(err, results) {
          return cb(err, results);
        });
      }
    ], function(err, results) {
      if (results != null) {
        return res.render("./page/setting", {
          web: results[0].data,
          weixin: results[1].data
        });
      } else {
        return res.status(500).end();
      }
    });
  };

  exports.productList = function(req, res) {
    return ProductCtrl.list(req.session.member.ent._id, function(err, results) {
      if (results.data != null) {
        return res.render("./page/productList", {
          products: results.data
        });
      } else {
        return res.status(500).end();
      }
    });
  };

  exports.userList = function(req, res) {
    return CustomerCtrl.list(req.session.member.ent._id, function(err, results) {
      if (results.data != null) {
        return res.render("./page/userList", {
          customers: results.data
        });
      } else {
        return res.status(500).end();
      }
    });
  };

  exports.members = function(req, res) {
    return MemberCtrl.fulllist(req.session.member.ent._id, function(err, results) {
      if (results.data != null) {
        return res.render("./page/members", {
          members: results.data
        });
      } else {
        return res.status(500).end();
      }
    });
  };

  exports.couponList = function(req, res) {
    return CouponCtrl.list(req.session.member.ent._id, function(err, results) {
      console.log(JSON.stringify(results));
      if (results.data != null) {
        return res.render("./page/couponList", {
          coupons: results.data,
          types: ["金额券", "折扣券", "产品固定价格", "免费券"]
        });
      } else {
        return res.status(500).end();
      }
    });
  };

}).call(this);
