// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl;

  MemberCtrl = require("./../ctrl/memberCtrl");

  exports.auth = function(req, res, next) {
    var token, tokenExpires;
    token = req.cookies.token || req.flash("token");
    tokenExpires = req.cookies.tokenExpires || req.flash("tokenExpires");
    if ((token != null) && tokenExpires > Date.now()) {
      req.session.flash = {};
      return MemberCtrl.memberInfo(token, function(err, results) {
        if (results.data != null) {
          req.session.member = results.data.member;
          return next();
        } else {
          return res.json({
            error: 502
          });
        }
      });
    } else {
      return res.json({
        error: 502
      });
    }
  };

}).call(this);
