// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl;

  MemberCtrl = require("./../ctrl/memberCtrl");

  exports.index = function(req, res) {
    var token, tokenExpires;
    token = req.cookies.token || req.flash("token");
    tokenExpires = req.cookies.tokenExpires || req.flash("tokenExpires");
    if ((token != null) && tokenExpires > Date.now()) {
      req.session.flash = {};
      return MemberCtrl.memberInfo(token, function(err, results) {
        if (results.data != null) {
          req.session.member = results.data.member;
          return res.render("index", {
            member: results.data.member
          });
        } else {
          return res.render("login");
        }
      });
    } else {
      return res.render("login");
    }
  };

}).call(this);
