// Generated by CoffeeScript 1.8.0
(function() {
  var MemberCtrl, WeixinCtrl, async;

  MemberCtrl = require("./../ctrl/memberCtrl");

  WeixinCtrl = require("./../ctrl/weixinCtrl");

  async = require("async");

  exports.index = function(req, res) {
    var token, tokenExpires;
    token = req.cookies.token || req.flash("token");
    tokenExpires = req.cookies.tokenExpires || req.flash("tokenExpires");
    if ((token != null) && tokenExpires > Date.now()) {
      req.session.flash = {};
      return MemberCtrl.memberInfo(token, function(err, results) {
        if (results.data != null) {
          req.session.member = results.data.member;
          return res.render("index", {
            member: results.data.member
          });
        } else {
          return res.render("login");
        }
      });
    } else {
      return res.render("login");
    }
  };

  exports.bind = function(req, res) {
    return async.parallel([
      function(cb) {
        return cb(null, "123123123123123");
      }, function(cb) {
        var url;
        url = "http://" + req.hostname + req.url;
        return WeixinCtrl.jsapiSign(weixinEnt, url, function(err, results) {
          return cb(err, results);
        });
      }
    ], function(err, results) {
      console.log(err, results);
      return res.render("weixinBind", {
        weixin: results[1].data,
        openid: results[0]
      });
    });
  };

}).call(this);
