// Generated by CoffeeScript 1.8.0
(function() {
  var CustomerCtrl;

  CustomerCtrl = (function() {
    var config, request;

    function CustomerCtrl() {}

    request = require("request");

    config = require("./../config/config.json");

    CustomerCtrl.list = function(ent, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/api/customer/fulllist?ent=" + ent;
      return request({
        url: url,
        timeout: 3000,
        method: "GET"
      }, function(err, response, body) {
        var error, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = JSON.parse(body);
            if ((res.error != null) === 1) {
              return fn(new Error(res.errMsg));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            error = _error;
            return fn(new Error("Parse Error"));
          }
        }
      });
    };

    return CustomerCtrl;

  })();

  module.exports = CustomerCtrl;

}).call(this);
