// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCtrl, config, request;

  request = require("request");

  config = require("./../config/config.json");

  WeixinCtrl = (function() {
    function WeixinCtrl() {}

    WeixinCtrl.jsapiSign = function(ent, posturl, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/jsapisign/" + ent;
      return request({
        url: url,
        timeout: 3000,
        method: "POST",
        form: {
          url: posturl
        }
      }, function(err, response, body) {
        var error, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = JSON.parse(body);
            if ((res.error != null) === 1) {
              return fn(new Error(res.errMsg));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            error = _error;
            return fn(new Error("Parse Error"));
          }
        }
      });
    };

    WeixinCtrl.getOpenid = function(ent, code, fn) {
      var url;
      url = "" + config.weixin.host + ":" + config.weixin.port + "/weixin/codeAccesstoken/" + ent + "?code=" + code;
      return request({
        url: url,
        timeout: 3000,
        method: "GET"
      }, function(err, response, body) {
        var error, res;
        if (err) {
          return fn(err);
        } else {
          try {
            res = JSON.parse(body);
            if ((res.error != null) === 1) {
              return fn(new Error(res.errMsg));
            } else {
              return fn(null, res);
            }
          } catch (_error) {
            error = _error;
            return fn(new Error("Parse Error"));
          }
        }
      });
    };

    return WeixinCtrl;

  })();

  module.exports = WeixinCtrl;

}).call(this);
