// Generated by CoffeeScript 1.8.0
(function() {
  var CouponCtrl, QRCodeExtend, async, createFun;

  CouponCtrl = require("./../ctrl/couponCtrl");

  QRCodeExtend = require("./../tools/qrcodeExtend");

  async = require("async");

  createFun = function(text) {
    return function(cb) {
      return QRCodeExtend.toPngFile(coupon._id, null, 3, function(err, res) {
        return cb(err, res);
      });
    };
  };

  CouponCtrl.marketingList("550f7c079270a9154dfbdc1f", function(err, res) {
    var coupon, data, funcArr;
    data = res.data;
    funcArr = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = res.length; _i < _len; _i++) {
        coupon = res[_i];
        _results.push(createFun(coupon._id));
      }
      return _results;
    })();
    return async.parallel(funcArr, function(err, results) {
      return console.log(err, results);
    });
  });

}).call(this);
